### ISSUE TITLE
Connectivity question

### ISSUE THREAD

**Issue by yagamosh** [ReverseEngineeringDE/iSmart-Gateway-Home-Assistant-Add-on#2]
Thanks for your great pioneering work here!

This is not an issue with your implementation, rather a call for help to see if I can make it work myself. 

I login to my app with a mobile number, do you know if this works with a mobile number instead of an email?
Also - I have a MG Marvel R (which also uses the iSmart app). Do you know if anyone has succeed to use this add-on for a Marvel R?

Currently I get the following message in the HA log and I suspect the login is not successful:
-----8<-----

SAIC-API Gateway running! Access the API endpoints via http://localhost:42042/ 
Accessed: /getData
Cooldown of 600 seconds is over and API request will be sent.
Sending login request...
Accessed: /getData
Cached output of vehicleResponse (implemented to reduce 12v battery drain). Cooldown seconds to next API request: 420

**Comment by markuswizard** [comment]
I use it successfully on my Marvel R but with email login. It's a bit buggy (I do not always get all sensor readings) but overall it's very useful.

**Comment by ReverseEngineeringDE** [comment]
Hey, thank you for the feedback! At the moment we are working on a big rework to improve the reliability (MQTT-server for example: https://github.com/ReverseEngineeringDE/SAIC-API-Documentation). The documentation is quite outdated at the moment - sorry for that.

Using a mobile number is actually not tested... So it is possible that I made a mistake in my gateway. You can switch to email via the offical app (but hopefully I will be able to upgrade the HA-Addon soon).

**Comment by yagamosh** [comment]
I can confirm it works with an email but not a mobile number. No worries about any outdated documentation, I so appreciate the work you put into this, and I'm sure many more are. I did notice that the api seems to respond with a bit of funny information, e.g. my State of Charge is 102.3% pretty much all the time.
